<script src="{{ asset('frontend/js/jquery-3.6.1.min.js') }}"></script>
<script src="{{ asset('frontend/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('frontend/js/bootstrap-datepicker.min.js') }}"></script>
<!--<script src="js/jquery-ui.js"></script>-->
<script src="{{ asset('frontend/js/jquery.magnific-popup.min.js') }}"></script>
<script src="{{ asset('frontend/js/owl.carousel.min.js') }}"></script>
<script src="{{ asset('frontend/js/wow.min.js') }}"></script>
<script src="{{ asset('frontend/js/select2.full.js') }}"></script>
<script src="{{ asset('frontend/js/jquery.waypoints.min.js') }}"></script>
<script src="{{ asset('frontend/js/moment.min.js') }}"></script>
<script src="{{ asset('frontend/js/jquery.meanmenu.js') }}"></script>
<script src="{{ asset('frontend/js/timeline-tab.js') }}"></script>
{{-- <script src="{{ asset('frontend/tinymce/tinymce.min.js') }}"></script> --}}
<script src="{{ asset('backend/js/toastr.min.js') }}"></script>
<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
